samples_narrow:
    - GM12878_ChIP_CTCF_1_BB_ENCFF000ARV
    - GM12878_ChIP_CTCF_1_JS_ENCFF001HHX
    - GM12878_ChIP_CTCF_1_MS_ENCFF000VUW
    - GM12878_ChIP_CTCF_1_VI_ENCFF000ROU
    - GM12878_ChIP_CTCF_2_BB_ENCFF000ARP
    - GM12878_ChIP_CTCF_2_JS_ENCFF001HIA
    - GM12878_ChIP_CTCF_2_MS_ENCFF000VUU
    - GM12878_ChIP_CTCF_2_VI_ENCFF000ROZ
    - GM12878_ChIP_CTCF_3_VI_ENCFF000ROX
samples_broad:
    - GM12878_ChIP_H3K27me3_1_JS_ENCFF001EXM
    - GM12878_ChIP_H3K27me3_2_BB_ENCFF000ASV
    - GM12878_ChIP_H3K36me3_1_JS_ENCFF001EXY
    - GM12878_ChIP_H3K36me3_2_BB_ENCFF000ATJ
    - GM12878_ChIP_H3K79me2_1_BB_ENCFF000AUD
    - GM12878_ChIP_H3K79me2_2_BB_ENCFF000AUC
controls:
    - GM12878_ChIP_IgG_lc_control_1_MS_ENCFF000VWF
    - GM12878_ChIP_IgG_mm_control_1_MS_ENCFF000VWD
idx_bt1: /fdb/igenomes/Homo_sapiens/UCSC/hg19/Sequence/BowtieIndex/genome
macs_g: hs